# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Evoweb\EwLlxml2xliff\:
    resource: '../Classes/*'

  Evoweb\EwLlxml2xliff\Controller\FileController:
    tags: [ 'backend.controller' ]